spring.application.name=InvoiceManagement
spring.datasource.url=jdbc:sqlserver://mssqlstud.fhict.local;databaseName=dbi468866_test;trustServerCertificate=true;
spring.datasource.username=dbi468866_test
spring.datasource.password=test
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=true
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto = create-drop
server.port=3000
